 version: '3.8'

 services:
   mysql-server:
       image: mysql:latest
       container_name: mysql-server
       environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: user_tracker
       ports:
         - "3306:3306"
       volumes:
         - mysql-data:/var/lib/mysql
         - ./init.sh:/docker-entrypoint-initdb.d/init.sh
       healthcheck:
         test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
         interval: 10s
         retries: 5
         start_period: 30s
         timeout: 10s

   user-command-service:
     build:
       context: ./user-service
       dockerfile: Dockerfile.command
     container_name: user-command-service
     environment:
       - USER_SERVICE_DB_HOST=mysql-server 
       - USER_SERVICE_DB_PORT=3306
       - USER_SERVICE_DB_USER=root
       - USER_SERVICE_DB_PASS=root
       - USER_SERVICE_DB_NAME=user_tracker
     ports:
       - "3001:3001"
     depends_on:
       mysql-server:
         condition: service_healthy

   user-query-service:
     build:
       context: ./user-service
       dockerfile: Dockerfile.query
     container_name: user-query-service
     ports:
       - "3000:3000"
     environment:
       - USER_SERVICE_DB_HOST=mysql-server 
       - USER_SERVICE_DB_PORT=3306
       - USER_SERVICE_DB_USER=root
       - USER_SERVICE_DB_PASS=root
       - USER_SERVICE_DB_NAME=user_tracker
     depends_on:
       mysql-server:
         condition: service_healthy

 volumes:
   mysql-data:

