version: '3.8' 

services:
  user-service:
    build: 
      context: ./user-service
      dockerfile: Dockerfile 
    container_name: user-service
    ports: 
      - "3000:3000"
    environment:
      - USER_SERVICE_DB_HOST=mysql-server 
      - USER_SERVICE_DB_PORT=3306
      - USER_SERVICE_DB_USER=root
      - USER_SERVICE_DB_PASS=root
      - USER_SERVICE_DB_NAME=user_tracker
    depends_on: 
      - mysql-server 

  mysql-server:
    image: mysql:latest
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_tracker
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

volumes:
  mysql_data:
